Repository WildCodeSchool-2024-02/toulouse-babyplace, pull requests merged in 2024-07, with the labels that each got.

#55 S4 us01/signupauthentification
  client/src/main.jsx
  client/src/pages/SignUp/SignUp-Done/SignUpDone.jsx
  client/src/pages/SignUp/SignUp.jsx
  package-lock.json
  server/app/controllers/customerActions.js
  server/app/middlewares/hashPassword.middleware.js
  server/app/routers/api/childcareCenter/router.js
  server/app/routers/api/customer/router.js
  server/database/fixtures/CustomerSeeder.js
  server/database/fixtures/customerSeeder.js
  server/database/models/ChildrenRepository.js
  server/database/models/CustomerRepository.js
  server/database/schema.sql
Labels: REVIEWED

#57 S5 us4/login
  client/package.json
  client/src/components/AuthenticationInput/AuthenticationInput.jsx
  client/src/components/AuthenticationInput/AuthenticationInput.scss
  client/src/pages/Profile/Profile.jsx
  client/src/pages/Profile/Profile.scss
  server/app/controllers/customerActions.js
  server/app/routers/api/customer/router.js
  server/database/fixtures/CustomerSeeder.js
  server/database/models/CustomerRepository.js
  server/database/schema.sql
Labels: CHANGES REQUESTED, REVIEWED

#58 S4 us08/calendar
  client/src/components/ProfileCenter/ChildCareCenterProfile.jsx
  client/src/components/ProfileCenter/ChildCareCenterProfile.scss
  client/src/main.jsx
  client/src/pages/ChildCareCenterProfile/ChildCareCenterPage.jsx
  client/src/pages/ChildCareCenterProfile/ChildCareCenterPage.scss
  client/src/pages/SignUp/SignUp-Done/SignUpDone.jsx
  client/src/pages/SignUp/SignUp.jsx
  server/database/fixtures/CustomerSeeder.js
Labels: REVIEWED

#59 S4 us01/sign up pro
  client/src/App.scss
  client/src/components/AuthenticationInput/AuthenticationInput.jsx
  client/src/components/Fieldset/Fieldset.jsx
  client/src/components/Fieldset/Fieldset.scss
  client/src/components/Input/Input.jsx
  client/src/components/Input/Input.scss
  client/src/components/NavBarSignUpPro/NavBarSignUpPro.jsx
  client/src/components/NavBarSignUpPro/NavBarSignUpPro.scss
  client/src/components/SignUpPro/ChildcareCenterStructure/ChildcareCenterStructure.jsx
  client/src/components/SignUpPro/ChildcareCenterStructure/ChildcareCenterStructure.scss
  client/src/components/SignUpPro/SignUpProCapacity/SignUpProCapacity.jsx
  client/src/components/SignUpPro/SignUpProDescription/SignUpProDescription.jsx
  client/src/components/SignUpPro/SignUpProDescription/SignUpProDescription.scss
  client/src/components/SignUpPro/SignUpProImages/SignUpProImages.jsx
  client/src/components/SignUpPro/SignUpProLocalisation/SignUpProLocalisation.jsx
  client/src/components/SignUpPro/SignUpProLocalisation/SignUpProLocalisation.scss
  client/src/components/SignUpPro/SignUpProLogin/SignUpProLogin.jsx
  client/src/components/SignUpPro/SignUpProLogin/SignUpProLogin.scss
  client/src/components/SignUpPro/SignUpProRules/SignUpProRules.jsx
  client/src/components/SignUpPro/SignUpProRules/SignUpProRules.scss
  client/src/components/SignUpPro/SignUpProSchedules/SignUpProSchedules.jsx
  client/src/context/SignUpPro.jsx
  client/src/main.jsx
  client/src/pages/SignUpPro/ChildcareCenterStructure/ChildcareCenterStructure.jsx
  client/src/pages/SignUpPro/SignUpPro.jsx
  client/src/pages/SignUpPro/SignUpPro.scss
  client/src/pages/SignUpPro/SignUpProImages/SignUpProImages.jsx
  client/src/pages/SignUpPro/SignUpProLocalisation/SignUpProLocalisation.jsx
  client/src/pages/SignUpPro/SignUpProLogin/SignUpProLogin.jsx
  client/src/pages/SignUpPro/SignUpProRules/SignUpProRules.jsx
  client/src/pages/SignUpPro/SignUpProRules/SignUpProRules.scss
  server/app/controllers/childcareCenterActions.js
  server/app/routers/api/childcareCenter/router.js
  server/app/routers/api/router.js
  server/database/models/ChildcareCenterRepository.js
  server/database/schema.sql
Labels: REVIEWED

#60 S4 us01/sign up pro
  client/src/components/NavBarSignUpPro/NavBarSignUpPro.jsx
  client/src/components/NavBarSignUpPro/NavBarSignUpPro.scss
  client/src/components/SignUpPro/SignUpProDescription/SignUpProDescription.jsx
  client/src/components/SignUpPro/SignUpProDescription/SignUpProDescription.scss
Labels: REVIEWED

#62 S5 us4/login
  client/package.json
  client/src/components/NavBarProfile/NavBarProfile.jsx
  client/src/pages/Profile/Profile.jsx
  package-lock.json
  server/app/controllers/customerActions.js
  server/app/middlewares/verifyPassword.middleware.js
  server/database/fixtures/Customer.Seeder.js
Labels: REVIEWED

#63 S6 us2/passwordcondition
  client/src/main.jsx
  client/src/pages/SignUp/SignUp-Done/SignUpDone.jsx
  client/src/pages/SignUp/SignUp.jsx
  client/src/pages/SignUp/SignUp.scss
  server/database/fixtures/Customer.Seeder.js
  server/database/models/CustomerRepository.js
  server/database/schema.sql
Labels: REVIEW REQUESTED

#64 S6 us07/search
  client/src/main.jsx
  client/src/pages/Search/Search.jsx
  client/src/pages/Search/Search.scss
  package-lock.json
  server/app/controllers/childcareCenterActions.js
  server/app/routers/api/childcareCenter/router.js
  server/database/fixtures/ChildcareCenterSeeder.js
  server/database/fixtures/ChildrenSeeder.js
  server/database/fixtures/CustomerSeeder.js
  server/database/fixtures/ExpTrainingSeeder.js
  server/database/fixtures/FilingSeeder.js
  server/database/models/ChildcareCenterRepository.js
  server/database/schema.sql
Labels: REVIEWED

#65 merge
  client/package.json
  client/src/components/NavBarProfile/NavBarProfile.jsx
  client/src/main.jsx
  client/src/pages/Profile/Profile.jsx
  client/src/pages/Search/Search.jsx
  client/src/pages/Search/Search.scss
  client/src/pages/SignUp/SignUp-Done/SignUpDone.jsx
  client/src/pages/SignUp/SignUp.jsx
  client/src/pages/SignUp/SignUp.scss
  server/app/controllers/childcareCenterActions.js
  server/app/controllers/customerActions.js
  server/app/middlewares/verifyPassword.middleware.js
  server/app/routers/api/childcareCenter/router.js
  server/database/fixtures/ChildcareCenterSeeder.js
  server/database/fixtures/ChildrenSeeder.js
  server/database/fixtures/CustomerSeeder.js
  server/database/fixtures/ExpTrainingSeeder.js
  server/database/fixtures/FilingSeeder.js
  server/database/models/ChildcareCenterRepository.js
  server/database/models/CustomerRepository.js
  server/database/schema.sql
Labels: REVIEWED

#67 feat: restructuration of tables
  server/app/controllers/childrenActions.js
  server/app/controllers/expTrainingActions.js
  server/app/controllers/filingActions.js
  server/app/controllers/itemActions.js
  server/app/routers/api/children/router.js
  server/app/routers/api/expTraining/router.js
  server/app/routers/api/filing/router.js
  server/app/routers/api/router.js
  server/database/models/ChildCareCenterCustomerRepository.js
  server/database/models/ChildrenRepository.js
  server/database/models/ExpTrainingRepository.js
  server/database/models/FilingRepository.js
  server/database/schema.sql
  server/database/tables.js
Labels: REVIEWED

#68 main
  server/app/controllers/childrenActions.js
  server/app/controllers/expTrainingActions.js
  server/app/controllers/filingActions.js
  server/app/controllers/itemActions.js
  server/app/routers/api/children/router.js
  server/app/routers/api/expTraining/router.js
  server/app/routers/api/filing/router.js
  server/app/routers/api/router.js
  server/database/models/ChildCareCenterCustomerRepository.js
  server/database/models/ChildrenRepository.js
  server/database/models/ExpTrainingRepository.js
  server/database/models/FilingRepository.js
  server/database/schema.sql
  server/database/tables.js
Labels: REVIEWED

#66 S4 us08/calendar
  client/src/assets/images/nounou.jpg
  client/src/components/Button/Button.jsx
  client/src/components/Button/Button.scss
  client/src/components/ProfileCenter/ChildCareCenterProfile.jsx
  client/src/components/ProfileCenter/ChildCareCenterProfile.scss
  client/src/components/WaitingList/TableComponent.jsx
  client/src/components/WaitingList/TableComponent.scss
  client/src/main.jsx
  client/src/pages/ChildCareCenterProfile/ChildCareCenterPage.jsx
  client/src/pages/ChildCareCenterProfile/ChildCareCenterPage.scss
  client/src/pages/PersonalPage/PersonalPage.jsx
Labels: CORRECTIONS DONE, REVIEWED

#70 feat: fetch nounous
  client/src/assets/images/2.png
  client/src/components/ProfileCenter/ChildCareCenterProfile.jsx
  client/src/components/ProfileCenter/ChildCareCenterProfile.scss
  client/src/pages/Profile/Profile.jsx
Labels: REVIEW REQUESTED

#73 S6 us07/search
  client/index.html
  client/src/App.jsx
  client/src/App.scss
  client/src/components/Footer/Footer.jsx
  client/src/components/Footer/Footer.scss
  client/src/components/NavBar/NavBar.scss
  client/src/pages/Search/Search.jsx
  client/src/pages/Search/Search.scss
  client/src/variables.scss
Labels: REVIEWED

#75 S6 us07/search
  client/src/components/Footer/Footer.jsx
  client/src/components/Footer/Footer.scss
  client/src/pages/Search/Search.jsx
  client/src/pages/Search/Search.scss
Labels: REVIEWED

#76 S5 us4/login
  client/src/components/Calendar/Calendar.jsx
  client/src/components/NavBarProfile/NavBarProfile.jsx
  client/src/components/ProfileCenter/ChildCareCenterProfile.jsx
  client/src/components/ProfileCenter/ChildCareCenterProfile.scss
  client/src/pages/Profile/Profile.jsx
  client/src/pages/Profile/Profile.scss
  client/src/services/tools/FaqData.js
Labels: REVIEWED

#77 feat: table component
  client/src/components/NavBarProfile/NavBarProfile.jsx
  client/src/components/NavBarProfile/NavBarProfile.scss
  client/src/components/WaitingList/TableComponent.jsx
  client/src/pages/Profile/Profile.jsx
  client/src/pages/Profile/Profile.scss
Labels: REVIEW REQUESTED, REVIEWED

#78 feat: deconnexion done
  client/src/App.jsx
  client/src/components/Footer/Footer.jsx
  client/src/components/NavBar/NavBar.jsx
  client/src/components/NavBar/NavBar.scss
  client/src/components/WaitingList/TableComponent.jsx
  client/src/components/WaitingList/TableComponent.scss
  client/src/pages/PersonalPage/PersonalPage.jsx
Labels: REVIEWED

#79 S6 us07/search
  client/src/components/AuthenticationInputPro/AuthenticationInputPro.jsx
  client/src/components/AuthenticationInputPro/AuthenticationInputPro.scss
  client/src/components/Footer/Footer.jsx
  client/src/main.jsx
  client/src/pages/ProfilePro/ProfilePro.jsx
  client/src/pages/ProfilePro/ProfilePro.scss
  client/src/pages/Search/Search.jsx
  client/src/pages/Search/Search.scss
  client/src/pages/SignInPro/SignInPro.jsx
  client/src/pages/SignUpPro/SignUpPro.jsx
  client/src/services/tools/FaqData.js
  package-lock.json
  server/app/controllers/childcareCenterActions.js
  server/app/middlewares/verifyPasswordPro.middleware.js
  server/app/routers/api/childcareCenter/router.js
  server/database/fixtures/ChildcareCenterSeeder.js
  server/database/models/ChildcareCenterRepository.js
  server/database/schema.sql
Labels: REVIEWED

#80 S5 us4/login
  client/src/components/Footer/Footer.jsx
  client/src/components/NavBar/NavBar.jsx
Labels: REVIEWED

#81 S8 us15/profile modification
  client/src/App.jsx
  client/src/App.scss
  client/src/components/Footer/Footer.jsx
  client/src/components/Footer/Footer.scss
  client/src/main.jsx
  client/src/pages/Profile/Profile.jsx
  client/src/pages/Profile/Profile.scss
  server/app/controllers/customerActions.js
  server/app/routers/api/customer/router.js
  server/database/fixtures/ChildcareCenterSeeder.js
  server/database/fixtures/CustomerSeeder.js
  server/database/models/CustomerRepository.js
Labels: REVIEWED

#82 S5 us4/login
  client/src/components/Footer/Footer.jsx
  client/src/components/Footer/Footer.scss
  client/src/components/NavBar/NavBar.jsx
Labels: REVIEWED

#83 S4 us08/calendar
  client/src/components/Cards/Card.scss
  client/src/components/WaitingList/TableComponent.jsx
  client/src/components/WaitingList/TableComponent.scss
  client/src/pages/PersonalPage/PersonalPage.jsx
  client/src/pages/PersonalPage/PersonalPage.scss
Labels: REVIEWED

#85 S6 us07/search
  client/src/components/AuthenticationImgs/AuthenticationImgs.jsx
  client/src/components/AuthenticationImgs/AuthenticationImgs.scss
  client/src/components/AuthenticationInput/AuthenticationInput.scss
  client/src/pages/SignInPro/SignInPro.scss
Labels: REVIEWED

#86 S8 us15/profile modification
  client/src/pages/Help/Help.scss
  client/src/pages/Search/Search.scss
  client/src/pages/SignUp/SignUp.scss
  client/src/pages/SignUpPro/SignUpPro.scss
  client/src/services/tools/FaqData.js
Labels: REVIEWED

#87 S4 us08/calendar
  client/src/components/WaitingList/TableComponent.jsx
  client/src/components/WaitingList/TableComponentAssmat.jsx
Labels: REVIEWED

#89 S5 us4/login
  client/src/components/modification/Modal.jsx
  client/src/components/modification/Modal.scss
  client/src/pages/PersonalPage/PersonalPage.scss
  client/src/pages/Profile/Profile.jsx
Labels: REVIEWED

#92 S6 us07/search
  client/index.html
  client/src/assets/images/logo.png
  client/src/components/NavBar/NavBar.jsx
  client/src/components/NavBar/NavBar.scss
  client/src/components/WaitingList/TableComponentAssmat.jsx
  client/src/pages/ProfilePro/ProfilePro.jsx
  server/app/controllers/childcareCenterActions.js
  server/app/routers/api/childcareCenter/router.js
  server/database/models/ChildcareCenterRepository.js
Labels: REVIEWED

#93 feat: change logo
  client/src/assets/images/logo.png
  client/src/components/NavBar/NavBar.scss
Labels: REVIEWED

#94 S5 us4/login
  client/src/assets/images/2.jpg
  client/src/assets/images/2.png
  client/src/assets/images/nounou.jpg
  client/src/components/AuthenticationImgs/AuthenticationImgs.jsx
  client/src/components/NavBar/NavBar.jsx
  client/src/main.jsx
  client/src/pages/Profile/Profile.jsx
  client/src/pages/Profile/Profile.scss
  client/src/pages/ProfilePro/ProfilePro.jsx
  client/src/pages/ProfilePro/ProfilePro.scss
  client/src/public/images/img_login.svg
  client/src/public/images/lumen-connexion.png
Labels: REVIEWED

#95 S8 us15/profile modification
  client/src/components/AuthenticationImgs/AuthenticationImgs.jsx
  client/src/components/AuthenticationImgs/AuthenticationImgs.scss
  client/src/components/Footer/Footer.scss
  client/src/pages/ProfilePro/ProfilePro.jsx
  client/src/pages/ProfilePro/ProfilePro.scss
  client/src/pages/Search/Search.jsx
Labels: REVIEWED

#97 S6 us07/search
  client/index.html
  client/src/components/AuthenticationImgs/AuthenticationImgs.jsx
  client/src/components/NavBar/NavBar.jsx
  client/src/components/SignUpPro/ChildcareCenterStructure/ChildcareCenterStructure.jsx
  client/src/public/images/logo.png
Labels: REVIEWED

#98 S8 us15/profile modification
  client/src/pages/ProfilePro/ProfilePro.jsx
  client/src/pages/ProfilePro/ProfilePro.scss
  server/app/controllers/childcareCenterActions.js
Labels: REVIEWED

#100 feat: add days in searchCard
  client/src/pages/Search/Search.jsx
Labels: REVIEWED

#101 S6 us07/search
  client/src/pages/Profile/Profile.jsx
  client/src/pages/ProfilePro/ProfilePro.jsx
Labels: REVIEWED
