Repository WildCodeSchool-2024-02/toulouse-babyplace, pull requests merged in 2024-06, with the labels that each got.

#1 feat: database
  client/src/App.css
  client/src/App.jsx
  client/src/assets/favicon.ico
  server/app/config.js
  server/database/fixtures/childcare_centerSeeder.js
  server/database/fixtures/childrenSeeder.js
  server/database/fixtures/customerSeeder.js
  server/database/fixtures/exp_trainingSeeder.js
  server/database/fixtures/filingSeeder.js
  server/database/models/childcare_centerRepository.js
  server/database/models/childrenRepository.js
  server/database/models/customerRepository.js
  server/database/models/exp_trainingRepository.js
  server/database/models/filingRepository.js
  server/database/schema.sql
  server/database/tables.js
  server/package.json
Labels: REVIEWED

#2 S2 us18/webpage
  client/index.html
  client/package.json
  client/src/App.jsx
  client/src/App.scss
  client/src/assets/images/easy-life.svg
  client/src/assets/images/intro.svg
  client/src/components/.gitkeep
  client/src/components/Footer/Footer.jsx
  client/src/components/Footer/Footer.scss
  client/src/components/NavBar/NavBar.jsx
  client/src/components/NavBar/NavBar.scss
  server/app/config.js
Labels: REVIEWED

#6 feat: router
  client/package.json
  package-lock.json
  server/app/routers/api/childcareCenter/router.js
  server/app/routers/api/children/router.js
  server/app/routers/api/customer/router.js
  server/app/routers/api/expTraining/router.js
  server/app/routers/api/filing/router.js
  server/app/routers/api/router.js
Labels: REVIEWED

#7 S3 us05/map
  client/package.json
  client/src/App.scss
  client/src/components/Footer/Footer.scss
  client/src/components/Map/Map.jsx
  client/src/components/Map/Map.scss
  client/src/components/NavBar/NavBar.jsx
  client/src/main.jsx
  client/src/services/tools/markerCoordinates.json
  package-lock.json
Labels: REVIEWED

#8 S3 us05/map
  client/src/App.css
  client/src/assets/images/iconMarker.png
  client/src/components/Map/Map.jsx
  client/src/services/tools/markerCoordinates.json
Labels: REVIEWED

#9 Dev dev
  client/index.html
  client/package.json
  client/src/App.css
  client/src/App.jsx
  client/src/App.scss
  client/src/assets/favicon.ico
  client/src/assets/images/easy-life.svg
  client/src/assets/images/iconMarker.png
  client/src/assets/images/intro.svg
  client/src/components/Footer/Footer.jsx
  client/src/components/Footer/Footer.scss
  client/src/components/Map/Map.jsx
  client/src/components/Map/Map.scss
  client/src/components/NavBar/NavBar.jsx
  client/src/components/NavBar/NavBar.scss
  client/src/main.jsx
  client/src/services/tools/markerCoordinates.json
  package-lock.json
  server/app/config.js
  server/app/controllers/childcareCenterActions.js
  server/app/controllers/childrenActions.js
  server/app/controllers/customerActions.js
  server/app/controllers/expTrainingActions.js
  server/app/controllers/filingActions.js
  server/app/controllers/itemActions.js
  server/app/routers/api/childcareCenter/router.js
  server/app/routers/api/children/router.js
  server/app/routers/api/customer/router.js
  server/app/routers/api/expTraining/router.js
  server/app/routers/api/filing/router.js
  server/app/routers/api/router.js
  server/database/fixtures/ChildcareCenterSeeder.js
  server/database/fixtures/CustomerSeeder.js
  server/database/fixtures/ExpTrainingSeeder.js
  server/database/fixtures/ItemSeeder.js
  server/database/fixtures/UserSeeder.js
  server/database/fixtures/childrenSeeder.js
  server/database/fixtures/filingSeeder.js
  server/database/models/AbstractRepository.js
  server/database/models/ChildcareCenterRepository.js
  server/database/models/ChildrenRepository.js
  server/database/models/CustomerRepository.js
  server/database/models/ExpTrainingRepository.js
  server/database/models/FilingRepository.js
  server/database/models/ItemRepository.js
  server/database/schema.sql
  server/database/tables.js
  server/package.json
Labels: REVIEWED

#10 fix: add public directory
  client/src/App.jsx
  client/src/public/images/background.webp
  client/src/public/images/easy-life.svg
  client/src/public/images/iconMarker.png
  client/src/public/images/intro.svg
Labels: REVIEWED

#11 fix image
  client/src/App.jsx
  client/src/public/images/background.webp
  client/src/public/images/easy-life.svg
  client/src/public/images/iconMarker.png
  client/src/public/images/intro.svg
Labels: REVIEWED

#12 S3 us05/map
  client/src/components/Map/Map.jsx
  client/src/public/images/iconMarker.png
Labels: REVIEWED

#13 into main
  client/src/components/Map/Map.jsx
  client/src/public/images/iconMarker.png
Labels: REVIEWED

#15 main
  client/src/components/Map/Map.jsx
  client/src/components/NavBar/NavBar.jsx
Labels: REVIEWED

#16 S3 us02/login page
  client/src/assets/images/img_login.svg
  client/src/assets/images/lumen-connexion.png
  client/src/components/AutenticationImgs/AutenticationImgs.jsx
  client/src/components/AutenticationImgs/AutenticationImgs.scss
  client/src/components/AutenticationInput/AutenticationInput.jsx
  client/src/components/AutenticationInput/AutenticationInput.scss
  client/src/components/NavBar/NavBar.jsx
  client/src/main.jsx
  client/src/pages/Login/Login.jsx
  client/src/pages/Login/Login.scss
  client/src/pages/SignUpPro/SignUpPro.jsx
  client/src/pages/SignUpPro/SignUpPro.scss
Labels: REVIEWED

#19 S3 us02/login page
  client/src/components/AuthenticationImgs/AuthenticationImgs.jsx
  client/src/components/AuthenticationImgs/AuthenticationImgs.scss
  client/src/components/AuthenticationInput/AuthenticationInput.jsx
  client/src/components/AuthenticationInput/AuthenticationInput.scss
  client/src/components/NavBar/NavBar.jsx
  client/src/main.jsx
  client/src/pages/Login/Login.jsx
  client/src/pages/SignIn/SignIn.jsx
  client/src/pages/SignIn/SignIn.scss
  client/src/pages/SignInPro/SignInPro.jsx
  client/src/pages/SignInPro/SignInPro.scss
  client/src/pages/SignUpPro/SignUpPro.jsx
  server/database/models/ChildcareCenterRepository.js
  server/database/models/ChildrenRepository.js
  server/database/models/CustomerRepository.js
  server/database/models/ExpTrainingRepository.js
  server/database/models/FilingRepository.js
Labels: CORRECTIONS DONE, REVIEWED

#21 S3 us05/map
  client/src/App.scss
  client/src/components/Footer/Footer.scss
  client/src/components/Map/Map.jsx
  client/src/components/Map/Map.scss
  client/src/components/NavBar/NavBar.jsx
  client/src/components/NavBar/NavBar.scss
  client/src/services/tools/markerCoordinates.json
  client/src/variables.scss
Labels: REVIEWED

#22 feat: signin
  client/src/components/AuthenticationImgs/AuthenticationImgs.jsx
  client/src/components/AuthenticationInput/AuthenticationInput.jsx
  client/src/main.jsx
  client/src/pages/SignIn/SignIn.jsx
  client/src/pages/SignUp/SignUp.jsx
  client/src/pages/SignUp/SignUp.scss
Labels: REVIEWED

#26 S4 us20/help
  client/src/App.jsx
  client/src/App.scss
  client/src/components/Footer/Footer.scss
  client/src/components/Layout/Layout.jsx
  client/src/components/NavBar/NavBar.jsx
  client/src/main.jsx
  client/src/pages/Help/Help.jsx
  client/src/pages/Help/Help.scss
Labels: REVIEWED

#27 S3 us01/clientsregistration
  client/src/pages/SignUp/SignUp.jsx
  client/src/pages/SignUp/SignUp.scss
  client/src/pages/SignUpPro/SignUpPro.scss
Labels: REVIEWED

#30 S3 us02/login page
  client/src/components/AuthenticationImgs/AuthenticationImgs.jsx
  client/src/components/AuthenticationImgs/AuthenticationImgs.scss
  package-lock.json
Labels: REVIEWED

#31 S4 us01/sign up pro
  client/src/App.scss
  client/src/components/AuthenticationImgs/AuthenticationImgs.scss
  client/src/components/AuthenticationInput/AuthenticationInput.jsx
  client/src/components/Button/Button.jsx
  client/src/components/Button/Button.scss
  client/src/components/Input/Input.jsx
  client/src/components/Input/Input.scss
  client/src/components/Layout/LayoutSignUpPro.jsx
  client/src/components/NavBar/NavBar.scss
  client/src/components/NavBarSignUpPro/NavBarSignUpPro.jsx
  client/src/components/NavBarSignUpPro/NavBarSignUpPro.scss
  client/src/components/SignUpProInfo/SignUpProInfo.jsx
  client/src/components/SignUpProInfo/SignUpProInfo.scss
  client/src/main.jsx
  client/src/pages/SignUpPro/ChildcareCenterStructure/ChildcareCenterStructure.jsx
  client/src/pages/SignUpPro/ChildcareCenterStructure/ChildcareCenterStructure.scss
  client/src/pages/SignUpPro/SignUpPro.jsx
  client/src/pages/SignUpPro/SignUpProImages/SignUpProImages.jsx
  client/src/pages/SignUpPro/SignUpProLocalisation/SignUpProLocalisation.jsx
  client/src/pages/SignUpPro/SignUpProLocalisation/SignUpProLocalisation.scss
  client/src/pages/SignUpPro/SignUpProLogin/SignUpProLogin.jsx
  client/src/pages/SignUpPro/SignUpProLogin/SignUpProLogin.scss
  client/src/variables.scss
Labels: REVIEWED

#33 S4 us20/help
  client/src/components/Accordion/Accordion.jsx
  client/src/components/Accordion/Accordion.scss
  client/src/components/Calendar/Calendar.jsx
  client/src/pages/Help/Help.jsx
  client/src/pages/Help/Help.scss
  client/src/pages/Reservation/Reservation.jsx
  client/src/services/tools/FaqData.js
  client/src/variables.scss
Labels: REVIEWED

#34 feat: profile page
  client/src/assets/images/2.jpg
  client/src/components/AuthenticationInput/AuthenticationInput.jsx
  client/src/components/AuthenticationInput/AuthenticationInput.scss
  client/src/components/NavBarProfile/NavBarProfile.jsx
  client/src/components/NavBarProfile/NavBarProfile.scss
  client/src/context/Auth.js
  client/src/main.jsx
  client/src/pages/Profile/Profile.jsx
  client/src/pages/Profile/Profile.scss
Labels: REVIEWED

#36 S4 us01/sign up pro
  client/src/components/AuthenticationInput/AuthenticationInput.scss
  client/src/components/Button/Button.jsx
  client/src/components/Button/Button.scss
  client/src/components/Fieldset/Fieldset.jsx
  client/src/components/Fieldset/Fieldset.scss
  client/src/components/Map/Map.scss
  client/src/components/NavBar/NavBar.scss
  client/src/main.jsx
  client/src/pages/SignUpPro/ChildcareCenterStructure/ChildcareCenterStructure.jsx
  client/src/pages/SignUpPro/ChildcareCenterStructure/ChildcareCenterStructure.scss
  client/src/pages/SignUpPro/SignUpProImages/SignUpProImages.jsx
  client/src/pages/SignUpPro/SignUpProLocalisation/SignUpProLocalisation.jsx
  client/src/pages/SignUpPro/SignUpProLogin/SignUpProLogin.jsx
  client/src/pages/SignUpPro/SignUpProRules/SignUpProRules.jsx
  client/src/pages/SignUpPro/SignUpProRules/SignUpProRules.scss
  client/src/variables.scss
Labels: CORRECTIONS DONE, REVIEWED

#38 S4 us01/sign up pro
  client/src/App.scss
  client/src/components/NavBarSignUpPro/NavBarSignUpPro.jsx
  client/src/components/NavBarSignUpPro/NavBarSignUpPro.scss
  client/src/pages/SignUpPro/ChildcareCenterStructure/ChildcareCenterStructure.jsx
  client/src/pages/SignUpPro/ChildcareCenterStructure/ChildcareCenterStructure.scss
  client/src/pages/SignUpPro/SignUpProImages/SignUpProImages.jsx
  client/src/pages/SignUpPro/SignUpProLocalisation/SignUpProLocalisation.jsx
  client/src/pages/SignUpPro/SignUpProLogin/SignUpProLogin.jsx
  client/src/pages/SignUpPro/SignUpProRules/SignUpProRules.jsx
Labels: REVIEWED

#39 S4 us20/help
  client/src/components/Accordion/Accordion.jsx
  client/src/components/Accordion/Accordion.scss
  client/src/pages/Help/Help.jsx
  client/src/pages/Help/Help.scss
Labels: REVIEWED

#40 dev into main
  client/src/App.scss
  client/src/components/Accordion/Accordion.jsx
  client/src/components/Accordion/Accordion.scss
  client/src/components/NavBarSignUpPro/NavBarSignUpPro.jsx
  client/src/components/NavBarSignUpPro/NavBarSignUpPro.scss
  client/src/pages/Help/Help.jsx
  client/src/pages/Help/Help.scss
  client/src/pages/SignUpPro/ChildcareCenterStructure/ChildcareCenterStructure.jsx
  client/src/pages/SignUpPro/ChildcareCenterStructure/ChildcareCenterStructure.scss
  client/src/pages/SignUpPro/SignUpProImages/SignUpProImages.jsx
  client/src/pages/SignUpPro/SignUpProLocalisation/SignUpProLocalisation.jsx
  client/src/pages/SignUpPro/SignUpProLogin/SignUpProLogin.jsx
  client/src/pages/SignUpPro/SignUpProRules/SignUpProRules.jsx
Labels: REVIEWED

#41 fix: correction seeder
  server/database/fixtures/ChildcareCenterSeeder.js
  server/database/fixtures/ExpTrainingSeeder.js
  server/database/fixtures/ItemSeeder.js
  server/database/fixtures/UserSeeder.js
  server/database/fixtures/childrenSeeder.js
  server/database/fixtures/customerSeeder.js
  server/database/fixtures/exp_trainingSeeder.js
  server/database/fixtures/filingSeeder.js
  server/database/tables.js
Labels: REVIEWED

#45 S4 us08/calendar
  client/package.json
  client/src/components/Calendar/Calendar.jsx
  client/src/components/Calendar/Calendar.scss
  client/src/pages/Reservation/Reservation.jsx
  client/src/pages/Reservation/Reservation.scss
  server/.eslintrc.json
  server/.prettierrc
  server/app/controllers/itemActions.js
  server/bin/migrate.js
  server/bin/seed.js
  server/database/client.js
  server/database/fixtures/AbstractSeeder.js
  server/database/fixtures/customerSeeder.js
  server/database/fixtures/filingSeeder.js
  server/index.js
  server/jest.config.js
  server/tests/config.js
  server/tests/install.test.js
Labels: CORRECTIONS DONE, REVIEWED

#46 S4 us01/sign up pro
  server/app/middlewares/hashPassword.middleware.js
  server/app/routers/api/childcareCenter/router.js
  server/database/fixtures/ChildcareCenterSeeder.js
  server/database/schema.sql
Labels: REVIEWED

#47 fix: fix name files
  server/database/fixtures/ErikSeeder.js
  server/database/fixtures/HenrySeeder.js
  server/database/fixtures/MatildaSeeder.js
  server/database/fixtures/customerSeeder.js
Labels: REVIEWED

#49 S5 us4/login
  package-lock.json
  server/app/controllers/customerActions.js
  server/app/middlewares/verifyPassword.middleware.js
  server/app/routers/api/customer/router.js
  server/database/models/CustomerRepository.js
  server/database/schema.sql
  server/package.json
Labels: REVIEW REQUESTED

#50 S4 us20/help
  client/src/App.scss
  client/src/components/NavBar/NavBar.jsx
  client/src/components/NavBar/NavBar.scss
  package-lock.json
  server/database/fixtures/CustomerSeeder.js
Labels: REVIEWED

#53 S4 us01/sign up pro
  client/src/App.jsx
  client/src/App.scss
  client/src/components/Button/Button.jsx
  client/src/components/Button/Button.scss
  client/src/components/Input/Input.scss
  client/src/pages/Reservation/Reservation.scss
  client/src/pages/SignUpPro/ChildcareCenterStructure/ChildcareCenterStructure.jsx
  client/src/pages/SignUpPro/ChildcareCenterStructure/ChildcareCenterStructure.scss
  client/src/pages/SignUpPro/SignUpPro.scss
  client/src/pages/SignUpPro/SignUpProImages/SignUpProImages.jsx
  client/src/pages/SignUpPro/SignUpProLocalisation/SignUpProLocalisation.jsx
  client/src/pages/SignUpPro/SignUpProLogin/SignUpProLogin.jsx
  client/src/pages/SignUpPro/SignUpProRules/SignUpProRules.jsx
  client/src/services/tools/typesChildcareCenter.js
Labels: REVIEWED

#54 dev to main
  client/package.json
  client/src/App.jsx
  client/src/App.scss
  client/src/components/Button/Button.jsx
  client/src/components/Button/Button.scss
  client/src/components/Calendar/Calendar.jsx
  client/src/components/Calendar/Calendar.scss
  client/src/components/Input/Input.scss
  client/src/components/NavBar/NavBar.jsx
  client/src/components/NavBar/NavBar.scss
  client/src/main.jsx
  client/src/pages/ChildCareCenterProfile/ChildCareCenterProfile.jsx
  client/src/pages/ChildCareCenterProfile/ChildCareCenterProfile.scss
  client/src/pages/Reservation/Reservation.jsx
  client/src/pages/Reservation/Reservation.scss
  client/src/pages/SignUpPro/ChildcareCenterStructure/ChildcareCenterStructure.jsx
  client/src/pages/SignUpPro/ChildcareCenterStructure/ChildcareCenterStructure.scss
  client/src/pages/SignUpPro/SignUpPro.scss
  client/src/pages/SignUpPro/SignUpProImages/SignUpProImages.jsx
  client/src/pages/SignUpPro/SignUpProLocalisation/SignUpProLocalisation.jsx
  client/src/pages/SignUpPro/SignUpProLogin/SignUpProLogin.jsx
  client/src/pages/SignUpPro/SignUpProRules/SignUpProRules.jsx
  client/src/services/tools/typesChildcareCenter.js
  package-lock.json
  server/.eslintrc.json
  server/.prettierrc
  server/app/config.js
  server/app/controllers/childcareCenterActions.js
  server/app/controllers/customerActions.js
  server/app/controllers/itemActions.js
  server/app/middlewares/hashPassword.middleware.js
  server/app/middlewares/verifyPassword.middleware.js
  server/app/routers/api/childcareCenter/router.js
  server/app/routers/api/customer/router.js
  server/app/routers/api/router.js
  server/bin/migrate.js
  server/bin/seed.js
  server/database/client.js
  server/database/fixtures/AbstractSeeder.js
  server/database/fixtures/ChildcareCenterSeeder.js
  server/database/fixtures/ChildrenSeeder.js
  server/database/fixtures/CustomerSeeder.js
  server/database/fixtures/ExpTrainingSeeder.js
  server/database/fixtures/FilingSeeder.js
  server/database/fixtures/ItemSeeder.js
  server/database/fixtures/UserSeeder.js
  server/database/fixtures/customerSeeder.js
  server/database/fixtures/exp_trainingSeeder.js
  server/database/fixtures/filingSeeder.js
  server/database/models/ChildcareCenterRepository.js
  server/database/models/CustomerRepository.js
  server/database/schema.sql
  server/database/tables.js
  server/index.js
  server/jest.config.js
  server/package.json
  server/tests/config.js
  server/tests/install.test.js
Labels: REVIEW REQUESTED
